### ISSUE TITLE
ImportError: cannot import name 'object_list_uid' from 'keras.utils.generic_utils'

### ISSUE THREAD

**Issue by jtlz2** [plaidml/plaidml#1840]
My StackOverflow question refers - https://stackoverflow.com/questions/68407043/how-do-i-fix-a-keras-error-for-a-plaidbench-keras-test

I am trying to install plaidml-keras so I can use non-Nvidia GPUs with Keras in python/jupyter. After clearing several other hurdles I get as far as:

```bash
plaidbench keras mobilenet
```
but it errors twice

    ImportError: cannot import name 'object_list_uid' from 'keras.utils.generic_utils' (/Users/me/sprinthive/src/notebooks/nbenv/lib/python3.7/site-packages/keras/utils/generic_utils.py)

    File "/Users/me/sprinthive/src/notebooks/nbenv/lib/python3.7/site-packages/plaidbench/frontend_keras.py", line 321, in __init__
    raise core.ExtrasNeeded(['plaidml-keras'])
    plaidbench.core.ExtrasNeeded: Missing needed packages for benchmark; to fix, pip install plaidml-keras

This is in spite of already having plaidml-keras installed:

```bash
pip freeze | grep plaid
plaidbench==0.6.4
plaidml==0.6.4
plaidml-keras==0.6.4
```

[I am using 0.6.4 to make it work on macOS 10.13 High Sierra]

How can I resolve the above errors?

Thanks!

**Comment by LLuke** [comment]
Here are my findings: 

It seems to me that plaidbench was not tested for certain python versions. Its translated error message also masked the issue. I used python 3.10 and got the same error message. The line 321 of /site-packages/plaidbench/frontend_keras.py is 

    importlib.import_module('plaidml.keras').install_backend()

I ran it manually and it actually throws the following ImportError

    ImportError: cannot import name 'Iterable' from 'collections' in Python

The Iterable class was removed from collections in Python 3.10 (details on this can be find at https://stackoverflow.com/a/72032097). Since the warning was added in python 3.9, I guess that plaidbench was developed and test primarily with python 3.8. With a fresh python 3.8 virtual environment and simply do

    pip install plaidml-keras plaidbench

Or recreated with the following requirements just in case you want to pin down the versions

```
cffi==1.16.0
click==8.1.7
colorama==0.4.6
enum34==1.1.10
h5py==3.10.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
numpy==1.24.4
plaidbench==0.7.0
plaidml==0.7.0
plaidml-keras==0.7.0
pycparser==2.21
PyYAML==6.0.1
scipy==1.10.1
six==1.16.0
```
then the error is gone.

This issue should be in plaidbench since it was the package that threw the final misleading error. However that project was archived on github so I'll keep the notes here only.
